global:
  scrape_interval: 2s # Как часто собирать метрики
  evaluation_interval: 2s # Как часто вычислять правила агрегации и алертинга

rule_files:
  - "alerts.yml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "app"
    static_configs:
      - targets: ["45.8.97.234:2112"]
